apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.services.payment.replicas | default 1 }}
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: payment
          image: {{ .Values.image.registry }}/{{ .Values.services.payment.image }}:{{ .Values.services.payment.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 10
