# PrometheusRule configuration for alerting on pod restarts in the "superheros" namespace
# This rule triggers an alert if any pod in the "superheros" namespace has restarted more than 0 times in the last 5 minutes

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: pod-restart-alerts
  namespace: superheros
  labels:
    release: monitoring

spec:
  groups:
    - name: kubernetes-alerts
      rules:
        - alert: PodRestartingFrequently
          expr: increase(kube_pod_container_status_restarts_total{namespace="superheros"}[5m]) > 0
          for: 1m

          labels:
            severity: warning
            team: platform

          annotations:
            summary: "Superhero application pod restarting"
            description: "Pod {{ $labels.pod }} restarted in namespace {{ $labels.namespace }}"