apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: monitoring
type: Opaque
stringData:
  SLACK_WEBHOOK_URL: "put-your-slack-webhook-url-here"
  OPENAI_API_KEY: "put-your-openai-api-key-here"