# Values for charts/app — rendered by Endurance
---
app:
    name: nginx-app
route:
    enabled: true
    path: /
    service: nginx-app
    port: 80
    gateway: istio-system/endurance-gateway
services:
    - name: nginx-app
      image: nginx
      tag: stable-alpine3.24-perl
      port: 80
      replicas: 1
      resources:
        requests:
            cpu: 50m
            memory: 64Mi
        limits:
            cpu: 500m
            memory: 512Mi
      security:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        allowPrivilegeEscalation: false
        dropCapabilities:
            - ALL
