## This Kyverno policy enforces that all Pods in the "superheros" namespace must have CPU and memory requests and limits defined. 
## It excludes Pods in the "kube-system", "istio-system", and "kyverno" namespaces from this requirement. 
## The policy will be enforced, meaning that any Pod that does not meet these criteria will be rejected when created or updated.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-resources
      match:
        resources:
          namespaces:
          - superheros
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
            - kube-system
            - istio-system
            - kyverno
      validate:
        message: "CPU and memory requests/limits are required"
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"

