namespace:
  name: superheros
image:
  registry: docker.io/dockergc00
services:
  frontend:
    enabled: true
    image: superheros-frontend
    replicas: 1
    tag: v1-7ba4230
    port: 80
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  catalog:
    enabled: true
    image: superheros-catalog
    port: 8081
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    versions:
      - name: superheros-catalog
        tag: v1-6f11a5d
        replicas: 1
        trafficWeight: 40
      - name: superheros-catalog
        tag: v2-6f11a5d
        replicas: 1
        trafficWeight: 30
      - name: superheros-catalog
        tag: v3-6f11a5d
        replicas: 1
        trafficWeight: 30
    tag: v1-5f0fb1b
  inventory:
    enabled: true
    image: superheros-inventory
    tag: v1-b9b34bb
    port: 8083
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  orders:
    enabled: true
    image: superheros-orders
    tag: v1-df408cf
    port: 8082
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  payment:
    enabled: true
    image: superheros-payment
    tag: v1-6f11a5d
    port: 8084
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
