namespace:
  name: superheros
image:
  registry: docker.io/dockergc00
services:
  frontend:
    enabled: true
    image: superheros-frontend
    replicas: 1
    tag: v1-00d7f9c
    port: 80
  catalog:
    enabled: true
    image: superheros-catalog
    port: 8081
    versions:
      - name: superheros-catalog
        tag: v1-ecb0994
        replicas: 1
        trafficWeight: 40
      - name: superheros-catalog
        tag: v2-ecb0994
        replicas: 1
        trafficWeight: 30
      - name: superheros-catalog
        tag: v3-ecb0994
        replicas: 1
        trafficWeight: 30
  inventory:
    enabled: true
    image: superheros-inventory
    tag: v1-b11ca3b
    port: 8083
  orders:
    enabled: true
    image: superheros-orders
    tag: v1-b62956e
    port: 8082
  payment:
    enabled: true
    image: superheros-payment
    tag: v1-47779b2
    port: 8084
