apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superheros
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/gc-ghub/project-gc-industries-devops-superheros.git
      targetRevision: HEAD
      path: gc-industries-devops-superheros/charts/app
      helm:
        valueFiles:
          - $values/gc-industries-devops-superheros/apps/superheros/values.yaml
    - repoURL: https://github.com/gc-ghub/project-gc-industries-devops-superheros.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: superheros
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
