# Values for charts/app — rendered by LaunchPad
---
app:
    name: superheros
services:
    - name: frontend
      image: dockergc00/superheros-frontend
      tag: v1-9c6f729
      port: 80
      replicas: 1
    - name: catalog
      image: dockergc00/superheros-catalog
      tag: v3-6f11a5d
      port: 8081
      replicas: 1
    - name: inventory
      image: dockergc00/superheros-inventory
      tag: v1-b9b34bb
      port: 8083
      replicas: 1
    - name: orders
      image: dockergc00/superheros-orders
      tag: v1-df408cf
      port: 8082
      replicas: 1
    - name: payment
      image: dockergc00/superheros-payment
      tag: v1-6f11a5d
      port: 8084
      replicas: 1
