name: CD - Frontend (GitOps)

on:
  workflow_run:
    workflows: ["CI - Frontend"]
    types:
      - completed

jobs:
  update-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        run: |
          echo "TAG=v1-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update Helm values
        run: |
          yq -i '.services.frontend.tag = env(TAG)' \
            gc-industries-devops-superheros/helm/superheros/values.yaml

      - name: Create branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b update-frontend-${TAG}

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(cd): update frontend image ${TAG}"

      - name: Push branch
        run: |
          git push origin update-frontend-${TAG}

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-frontend-${{ env.TAG }}
          title: "Update frontend image to ${{ env.TAG }}"
          body: |
            Auto-generated PR from CI pipeline.
            🔍 Awaiting Kyverno validation